_target_: navsim.agents.hidden.hidden_agent_v2.HiddenAgent
_convert_: 'all'

config:
  _target_: navsim.agents.hidden.hidden_config.HiddenConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: /mnt/ds/navsim-main/exp/training_hidden_v2_30e/2025.11.28.14.54.08/lightning_logs/version_0/checkpoints/e30.ckpt
lr: 1e-4
