_target_: navsim.agents.hidden_v2.hidden_agent.HiddenAgent
_convert_: 'all'

config:
  _target_: navsim.agents.hidden_v2.hidden_config.HiddenConfig
  _convert_: 'all'

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5

  latent: False

checkpoint_path: null
lr: 1e-4
